apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-1
spec:
  capacity:
    storage: 5Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below 
  nfs:
    server: fs-43145c02.efs.ap-southeast-1.amazonaws.com # Please change this to your NFS server
    path: /efs # Please change this to the relevant share
