apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ebs-1
#  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: "gp2"
  resources:
    requests:
      storage: 5Gi # volume size requested
